<?php

namespace Database\Seeders;

use Illuminate\Database\Eloquent\Factories\Sequence;
use Illuminate\Database\Seeder;

class HolidaySeeder extends Seeder
{
    public function run(): void
    {
        $superAdmin = \App\Models\User::where('system_role', true)->first();
        $city = \App\Models\City::where('id', 11524)->first();

        $values = [
            [
                'owner' => $superAdmin->id,
                'name' => 'Confraternização Universal',
                'country_id' => $city->country_id,
                'country_code' => $city->country_code,
                'authority' => 'federal',
                'day_off' => true,
                'day' => '01',
                'month' => '01',
                'start_time' => '00:00',
                'end_time' => '23:59:59',
            ],
            [
                'owner' => $superAdmin->id,
                'name' => 'Carnaval',
                'country_id' => $city->country_id,
                'country_code' => $city->country_code,
                'authority' => 'federal',
                'day_off' => true,
                'easter' => true,
                'sum_difference' => false,
                'difference_start' => "50 days",
                'difference_end' => "46 days 1 second",
            ],
            [
                'owner' => $superAdmin->id,
                'name' => 'Quarta-Feira de Cinzas',
                'country_id' => $city->country_id,
                'country_code' => $city->country_code,
                'authority' => 'federal',
                'day_off' => true,
                'easter' => true,
                'sum_difference' => false,
                'difference_start' => "46 days",
                'difference_end' => "45 days 10 hours",
            ],
            [
                'owner' => $superAdmin->id,
                'name' => 'Sexta-Feira Santa',
                'country_id' => $city->country_id,
                'country_code' => $city->country_code,
                'authority' => 'federal',
                'day_off' => true,
                'easter' => true,
                'sum_difference' => false,
                'difference_start' => "2 days",
                'difference_end' => "1 day 1 second",
            ],
            [
                'owner' => $superAdmin->id,
                'name' => 'Páscoa',
                'country_id' => $city->country_id,
                'country_code' => $city->country_code,
                'authority' => 'federal',
                'day_off' => false,
                'easter' => true,
                'sum_difference' => true,
                'difference_start' => "0 hours",
                'difference_end' => "23 hours 59 minutes 59 seconds",
            ],
            [
                'owner' => $superAdmin->id,
                'name' => 'Corpus Christi',
                'country_id' => $city->country_id,
                'country_code' => $city->country_code,
                'authority' => 'federal',
                'day_off' => true,
                'easter' => true,
                'sum_difference' => true,
                'difference_start' => "60 days",
                'difference_end' => "60 days 23 hours 59 minutes 59 seconds",
            ],
            [
                'owner' => $superAdmin->id,
                'name' => 'Tiradentes',
                'country_id' => $city->country_id,
                'country_code' => $city->country_code,
                'authority' => 'federal',
                'day_off' => true,
                'day' => '21',
                'month' => '04',
                'start_time' => '00:00',
                'end_time' => '23:59:59',
            ],
            [
                'owner' => $superAdmin->id,
                'name' => 'Dia mundial do Trabalho',
                'country_id' => $city->country_id,
                'country_code' => $city->country_code,
                'authority' => 'federal',
                'day_off' => true,
                'day' => '01',
                'month' => '05',
                'start_time' => '00:00',
                'end_time' => '23:59:59',
            ],
            [
                'owner' => $superAdmin->id,
                'name' => 'Independência do Brasil',
                'country_id' => $city->country_id,
                'country_code' => $city->country_code,
                'authority' => 'federal',
                'day_off' => true,
                'day' => '07',
                'month' => '09',
                'start_time' => '00:00',
                'end_time' => '23:59:59',
            ],
            [
                'owner' => $superAdmin->id,
                'name' => 'Dia de N. Sra. Aparecida',
                'country_id' => $city->country_id,
                'country_code' => $city->country_code,
                'authority' => 'federal',
                'day_off' => true,
                'day' => '12',
                'month' => '10',
                'start_time' => '00:00',
                'end_time' => '23:59:59',
            ],
            [
                'owner' => $superAdmin->id,
                'name' => 'Dia do Servidor Público',
                'country_id' => $city->country_id,
                'country_code' => $city->country_code,
                'authority' => 'federal',
                'day_off' => true,
                'day' => '28',
                'month' => '10',
                'start_time' => '00:00',
                'end_time' => '23:59:59',
            ],
            [
                'owner' => $superAdmin->id,
                'name' => 'Finados',
                'country_id' => $city->country_id,
                'country_code' => $city->country_code,
                'authority' => 'federal',
                'day_off' => true,
                'day' => '02',
                'month' => '11',
                'start_time' => '00:00',
                'end_time' => '23:59:59',
            ],
            [
                'owner' => $superAdmin->id,
                'name' => 'Proclamação da República',
                'country_id' => $city->country_id,
                'country_code' => $city->country_code,
                'authority' => 'federal',
                'day_off' => true,
                'day' => '15',
                'month' => '11',
                'start_time' => '00:00',
                'end_time' => '23:59:59',
            ],
            [
                'owner' => $superAdmin->id,
                'name' => 'Dia Nacional de Zumbi e da Consciência Negra',
                'country_id' => $city->country_id,
                'country_code' => $city->country_code,
                'authority' => 'federal',
                'day_off' => true,
                'day' => '20',
                'month' => '11',
                'start_time' => '00:00',
                'end_time' => '23:59:59',
            ],
            [
                'owner' => $superAdmin->id,
                'name' => 'Natal',
                'country_id' => $city->country_id,
                'country_code' => $city->country_code,
                'authority' => 'federal',
                'day_off' => true,
                'day' => '25',
                'month' => '12',
                'start_time' => '00:00',
                'end_time' => '23:59:59',
            ],
        ];

        \App\Models\Holiday::factory(count($values))
            ->state(new Sequence(...$values))
            ->create();
    }
}
